Add expressions and conditions
fedehuguet/tdd-compiler pull request #3
Opened 2019-10-22 04:01 UTC by tonyyasi

## What does this PR do?

- Add expressions to support addition, subtraction, division, multiplication, greater than, less than, and differences(!=).

- Support conditions (if, elseif, else)

TODO: support AND, OR and while loops.

2019-10-22 04:03 UTC, tonyyasi commented
Do you think you can check this out and possibly add the `&&`, `||` and `while` ? @fedehuguet 

I talked to bracho and handling just the while is good enough, apparently fors are hard, lol

2019-10-24 20:18 UTC, fedehuguet commented on tdd.g4
> +body: variable* statements;
Creo que aqui deberia ser statement*, porque luego statements solo es esa regla

2019-10-24 20:18 UTC, fedehuguet commented on tdd.g4
> +CHAR_VAL: '\'' (LOWER_CASE | UPPPER_CASE) '\'';
String val y charl_val deberian de tener lo mismo adentro, no creo que el ? aporte algo bien, deberia ser solo .*

2019-10-24 20:22 UTC, fedehuguet commented on tdd.g4
> +condition: IF condition_check OPEN_BLOCK body CLOSE_BLOCK | IF condition_check OPEN_BLOCK body CLOSE_BLOCK ELSE OPEN_BLOCK body CLOSE_BLOCK | IF condition_check OPEN_BLOCK body CLOSE_BLOCK (ELSEIF co
Creo que esto se podria resolver mejor agrupando lo que es igual (Left factoring), hara que sea mas entendible

2019-10-24 20:24 UTC, fedehuguet commented on tdd.g4
> +    | SUBSTRACT VALUE
Porque poner ADD VALUE y SUBSTRACT VALUE aqui? nunca lo he visto en los diagramas de la clase, y no creo que es necesario

2019-10-24 20:28 UTC, fedehuguet requested changes
Revisa los comentarios que deje por favor

2019-10-24 20:32 UTC, tonyyasi commented on tdd.g4
> +CHAR_VAL: '\'' (LOWER_CASE | UPPPER_CASE) '\'';
me salia un error raro si no ponia el `?` y supongo que ayuda para aceptar el string vacio. pero lo de char, si

2019-10-24 20:32 UTC, tonyyasi commented on tdd.g4
> +    | SUBSTRACT VALUE
me lo copie de una gramatica de la tarea hehehe

2019-10-24 20:33 UTC, tonyyasi commented on tdd.g4
> +body: variable* statements;
pero luego las vars? o agregar vars a statements?

2019-10-24 20:39 UTC, tonyyasi commented on tdd.g4
> +body: variable* statements;
ya entendi esto.

2019-10-24 20:39 UTC, fedehuguet commented on tdd.g4
> +body: variable* statements;
o sea lo mismo casi:
body: variable* statement*;
statement: sndflasnld

porque ahorita es:
body: variable statements
statements: statement*
statement: asflas

2019-10-24 20:40 UTC, fedehuguet commented on tdd.g4
> +body: variable* statements;
es innecesario el statements: statement*  , no crees?

2019-10-24 20:40 UTC, fedehuguet commented on tdd.g4
> +CHAR_VAL: '\'' (LOWER_CASE | UPPPER_CASE) '\'';
va lo dejamos asi

2019-10-29 21:16 UTC, merged